version: "3.8"
services:
  webapp:
    restart: unless-stopped
    build: .
    ##    ports:
    ##    - 3000:3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - node_network

  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 85:80
    depends_on:
      - webapp
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node_network

networks:
  node_network:
